version: 0.0
os: linux
files:
  - source: /*.jar
    destination: app/
hooks:
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 3600
  ValidateService:
    - location: scripts/monitor_service
      timeout: 3600
