#!/bin/bash
curl -O https://download.java.net/java/GA/jdk18.0.1.1/65ae32619e2f40f3a9af3af1851d6e19/2/GPL/openjdk-18.0.1.1_linux-x64_bin.tar.gz
tar zxvf openjdk-18.0.1.1_linux-x64_bin.tar.gz
mv jdk-18.0.1.1 /opt/
export JAVA_HOME=/opt/jdk-18.0.1.1
export PATH=$PATH:$JAVA_HOME/bin
